# https://github.com/marketplace/actions/setup-php-action
on: push
name: Build PHP application
permissions:
  contents: read
  issues: read
  checks: write
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-latest]
        php-versions: ['8.1','8.2']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with xdebug & tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: xdebug
          tools: php-cs-fixer, phpunit, composer:v2, psalm
          coverage: xdebug
        env:
          fail-fast: true
      - name: Install dependencies
        run: composer install --prefer-dist --working-dir=./src
      - name: Run Psalm
        run: psalm --output-format=github
      - name: Test
        run: |
          phpunit --configuration phpunit.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/logs/junit.xml
          event_name: ${{ github.event.workflow_run.event }}
      #- name: Publish code coverage
      #  uses: danhunsaker/clover-reporter-action@v0.2.17-clover
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    clover-file: ./build/logs/coverage.xml
  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/angular-githubaction/*"
          token: ${{ secrets.TOKEN }}
